icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#181818"
separator_fg = "#cb712a"
separator_bg = "#181818"
separator = "|"
good_bg = "#181818"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "battery"
interval = 10
device = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
